# -*- coding: utf-8 -*-
"""pandas_basic_dataframe

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1eYkvh_ev5CbfnqRZ5Y8ZvR2MDl0ymdQP
"""

import pandas as pd

df = pd.read_csv('https://raw.githubusercontent.com/prasertcbs/tutorial/master/mpg.csv')
df

df['cty_kml'] = df['cty']*0.425
df.head()

df['hwy_kml'] = df.hwy*0.425
df

df['cty_kml'] = df['cty_kml'].round(1)

df['trans_am'] = df.trans.str[0]
df.head()

df.cty_kml.mean()

df.hwy_kml.mean()

df.describe()