# -*- coding: utf-8 -*-
"""pandas_datatypes

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1VH92FpeD1gQAJdVhoJG68D1Tq7R467cy
"""

import pandas as pd
df = pd.read_table('https://github.com/prasertcbs/tutorial/raw/master/employee.tsv')
df.head()

df.info()

df = pd.read_table('https://github.com/prasertcbs/tutorial/raw/master/employee.tsv',parse_dates=['dob'])
df.head()

df.salary.mean()

df.salary.sum()

df.occupation.value_counts()

df.occupation.str.upper()

pd.to_datetime('today').year-df.dob.dt.year

df['age'] = pd.to_datetime('today').year-df.dob.dt.year
df

df.age.mean()

df.own_house.value_counts()

df.describe()

df.dob.dt.day_name()