# -*- coding: utf-8 -*-
"""pandas_head_tail_sample

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1ENTXohp6TQGOpN4Ko3USQPsJpQCQ4oRx
"""

import pandas as pd
pd.__version__

df = pd.read_csv('https://github.com/prasertcbs/tutorial/raw/master/thai_provinces.csv')
df.shape
df

df.head()

df.tail()

df.tail(10)

df[:5] # df.head()

df[-5:] #df.tail()

pd.concat([df.head(),df.tail()]) # ต่อข้อมูล Head กับ Tail

pd.concat([df.head(3),df.tail(3)])

df.sample()

df.sample(n=5)

df.sample(frac=.1) #สุ่มดูข้อมูล 10%

df.provinceTh.sample(n=5)

df.provinceTh.head()

df[['provinceTh','areaKm2']].head()

df[['provinceTh','areaKm2']].sample(n=5)