# -*- coding: utf-8 -*-
"""pandas_series

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/14xZg5AXdfV0zBV4H6cmY5PHAog4TXCPY
"""

import pandas as pd
sales = pd.Series([20,12,18,10])
sales

sales[1]

sales[2:]

sales[1:3]

sales * 33

sales.index

sales.sum()

sales.mean()

s = pd.Series([20,12,18,10],index = [['Jan','Feb','Mar','Apr']])
s

s['Feb']

# Commented out IPython magic to ensure Python compatibility.
# %matplotlib inline

s.plot()

s.plot(kind='bar')

coffee = pd.Series(['mocha','latte','espresso'])
coffee