# -*- coding: utf-8 -*-
"""pandas_boxplot

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/15x4zUYJhoWD6j9WEhNhuZZEKlx6gqOo4
"""

# Commented out IPython magic to ensure Python compatibility.
import pandas as pd
# %matplotlib inline
df = pd.read_csv('https://github.com/prasertcbs/tutorial/raw/master/mpg.csv')
df.sample(10)

df.cty.plot.box()

df.boxplot()

df[['cty','hwy']].plot.box()

df[['cty','hwy']].boxplot()

df[['cty','hwy']].boxplot();

df.boxplot(column=['cty','hwy'])

df.boxplot(column=['cty','hwy'],by = 'drv')

df.boxplot(column=['cty','hwy'],by = 'drv',grid = False)

df.boxplot(column='cty',by=['class','drv'])

df.boxplot(column='cty',by=['class','drv'],rot = 90,grid = False)

df.boxplot(column='cty',by=['class','drv'],vert = False,grid = False)

df.boxplot(column=['cty','hwy'],by=['class','drv'],vert = False,grid = False)

df.boxplot(column=['cty','hwy'],by=['class','drv'],vert = False,grid = False,figsize =(10,5))