# -*- coding: utf-8 -*-
"""pandas_basic_stat

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1MFKv8g7WRxPtKmNFOXAyGUWgmkK3dMeP
"""

import pandas as pd
df = pd.read_csv('https://raw.githubusercontent.com/prasertcbs/tutorial/master/mpg.csv')

df.head()

df.tail()

df.shape

df.info()

#สุ่มข้อมูล
df.sample(20)

df.mean()

df.median()

df.manufacturer.value_counts()

df['class'].value_counts()

df.describe()

#Transpose Table
df.describe().T

df.corr()

df.nlargest(5,columns='cty')