# -*- coding: utf-8 -*-
"""รู้จักกับ Pandas

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1rrRJPJc1jVdzGFWdueURyL8gXJ24cKiy
"""

import pandas as pd
df = pd.read_csv('https://github.com/prasertcbs/basic-dataset/raw/master/panel_data.csv')
df.head()

df[df.brand.str.contains('AUDI|BMW')]

df.info()

t = df.sum(numeric_only=True)
t

t.sort_values().plot(kind='barh');

df.drop(['month'],axis=1).groupby('brand').sum().nlargest(5,'total')

df.drop(['month'],axis=1).groupby('brand').sum().nlargest(5,'total') \
.plot(kind='barh',subplots=True,layout=(2,4),figsize=(12,5),sharey=True);

df.groupby('brand').sum().nsmallest(10,'total')

df.to_excel('Test_data.xlsx',index=False)